# ============================================================
# config.py — Backward-Compatibility Alias
#
# This module re-exports all settings from the Pydantic-based
# settings.py so existing `import config` / `config.XXX` code
# continues to work without any changes.
# ============================================================

import os
from settings import settings as _s

# Re-export every setting as a module-level attribute
SRC_DIR = _s.SRC_DIR
ENGINE_HOME = _s.ENGINE_HOME
BASE_DIR = _s.BASE_DIR
PROJECT_ROOT = _s.PROJECT_ROOT
DATA_DIR = _s.DATA_DIR
ASSETS_DIR = _s.ASSETS_DIR
TEMPLATE_PATH = _s.TEMPLATE_PATH
STYLE_PATH = _s.STYLE_PATH
TEMP_IMAGE_PATH = _s.TEMP_IMAGE_PATH
AUDIT_LOG_PATH = _s.AUDIT_LOG_PATH
APP_LOG_PATH = _s.APP_LOG_PATH
LOG_DIR = _s.LOG_DIR
LOGS_DIR = LOG_DIR
TODO_PATH = _s.TODO_PATH
DRAFTS_DIR = _s.DRAFTS_DIR
BROWSER_PROFILE_DIR = _s.BROWSER_PROFILE_DIR

MASTER_NAME = _s.MASTER_NAME
MASTER_USERNAME = _s.MASTER_USERNAME

TELEGRAM_BOT_TOKEN = _s.TELEGRAM_BOT_TOKEN
TELEGRAM_ADMIN_CHAT_ID = _s.TELEGRAM_ADMIN_CHAT_ID
PUBLIC_ACCESS_ALLOWED = _s.PUBLIC_ACCESS_ALLOWED

CLOUDINARY_CLOUD_NAME = _s.CLOUDINARY_CLOUD_NAME
CLOUDINARY_API_KEY = _s.CLOUDINARY_API_KEY
CLOUDINARY_API_SECRET = _s.CLOUDINARY_API_SECRET

INSTAGRAM_ACCESS_TOKEN = _s.INSTAGRAM_ACCESS_TOKEN
IG_BUSINESS_ID = _s.IG_BUSINESS_ID

OLLAMA_BASE_URL = _s.OLLAMA_BASE_URL
SGLANG_BASE_URL = _s.SGLANG_BASE_URL
OLLAMA_MODEL = _s.OLLAMA_MODEL
OLLAMA_MODEL_FAST = _s.OLLAMA_MODEL_FAST
OLLAMA_MODELS = _s.OLLAMA_MODELS

# Role-based models
OLLAMA_MODEL_REASONING = _s.OLLAMA_MODEL_REASONING
OLLAMA_MODEL_VISION = _s.OLLAMA_MODEL_VISION
OLLAMA_MODEL_CAPTION = _s.OLLAMA_MODEL_CAPTION
OLLAMA_MODEL_SUMMARY = _s.OLLAMA_MODEL_SUMMARY
OLLAMA_MODEL_CODE = _s.OLLAMA_MODEL_CODE
OLLAMA_MODEL_REVIEWER = _s.OLLAMA_MODEL_REVIEWER
OLLAMA_MODEL_INTENT = _s.OLLAMA_MODEL_INTENT

# Provider Switch
LLM_PROVIDER = _s.LLM_PROVIDER

# Groq Tiered
GROQ_MODEL = _s.GROQ_MODEL
GROQ_MODEL_HEAVY = _s.GROQ_MODEL_HEAVY
GROQ_MODEL_FAST = _s.GROQ_MODEL_FAST

# Gemini Integration
GEMINI_API_KEY = _s.GEMINI_API_KEY
GEMINI_MODEL = _s.GEMINI_MODEL
GEMINI_MODEL_HEAVY = _s.GEMINI_MODEL_HEAVY

VOICE_SERVER_URL = _s.VOICE_SERVER_URL

DAILY_TRIGGER_HOUR = _s.DAILY_TRIGGER_HOUR
DAILY_TRIGGER_MINUTE = _s.DAILY_TRIGGER_MINUTE

SELF_UPDATE_INTERVAL_HOURS = _s.SELF_UPDATE_INTERVAL_HOURS
UPDATE_HISTORY_DIR = _s.UPDATE_HISTORY_DIR
BACKUP_DIR = _s.BACKUP_DIR
MAX_BACKUPS = _s.MAX_BACKUPS
LOG_RETENTION_DAYS = _s.LOG_RETENTION_DAYS
SELF_ASSESSMENT_THRESHOLD = _s.SELF_ASSESSMENT_THRESHOLD
PROTECTED_FILES = _s.PROTECTED_FILES

MEMORY_STORE_DIR = _s.MEMORY_STORE_DIR
EMBED_MODEL = _s.EMBED_MODEL

SKILLS_DIR = _s.SKILLS_DIR
SKILLS_MD_PATH = _s.SKILLS_MD_PATH

CHAT_HISTORY_PATH = _s.CHAT_HISTORY_PATH
MAX_CHAT_HISTORY = _s.MAX_CHAT_HISTORY

PERSONA = _s.PERSONA
# ─── Knowledge & State ────────────────────────────────
STATE_PATH = _s.STATE_PATH
KNOWLEDGE_GRAPH_PATH = _s.KNOWLEDGE_GRAPH_PATH

EMAIL_IMAP_SERVER = _s.EMAIL_IMAP_SERVER
EMAIL_SMTP_SERVER = _s.EMAIL_SMTP_SERVER
EMAIL_ADDRESS = _s.EMAIL_ADDRESS
EMAIL_PASSWORD = _s.EMAIL_PASSWORD
EMAIL_SMTP_PORT = _s.EMAIL_SMTP_PORT

CALENDAR_PATH = _s.CALENDAR_PATH

API_HOST = _s.API_HOST
API_PORT = _s.API_PORT
WEBHOOK_SECRET = _s.WEBHOOK_SECRET
WEBHOOK_PORT = _s.WEBHOOK_PORT

ENCRYPTION_KEY_PATH = _s.ENCRYPTION_KEY_PATH
dash = _s.DASHBOARD_PORT
DASHBOARD_PORT = _s.DASHBOARD_PORT
TRACE_HISTORY_LIMIT = _s.TRACE_HISTORY_LIMIT
GROQ_API_KEY = _s.GROQ_API_KEY
OPENROUTER_API_KEY = _s.OPENROUTER_API_KEY
OPENROUTER_MODEL_FREE = _s.OPENROUTER_MODEL_FREE
GROQ_DAILY_LIMIT = _s.GROQ_DAILY_LIMIT
OPENROUTER_DAILY_LIMIT = _s.OPENROUTER_DAILY_LIMIT

REASONING_COMPLEXITY_THRESHOLD = _s.REASONING_COMPLEXITY_THRESHOLD
REASONING_MAX_RECURSION = _s.REASONING_MAX_RECURSION

# ── Auth ──────────────────────────────────────────────────────
MASTER_PASSWORD = _s.MASTER_PASSWORD
JWT_SECRET = os.environ.get("JWT_SECRET", "asura-sovereign-master-key-32byte")  # must be >= 32 bytes
API_KEY = os.environ.get("API_KEY", "asura-sk-sovereign-master-key")
